#!/usr/bin/env bash

set -e
set -ou pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
ROOT_DIR=$(dirname "$SCRIPT_DIR")

set -x

pytest "$ROOT_DIR"

isort --check "$ROOT_DIR"

black --check "$ROOT_DIR"
